name: Snapshot

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  snapshot:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code onto GOPATH
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: './go.mod'
          check-latest: true

      - name: Install bom
        uses: kubernetes-sigs/release-actions/setup-bom@10fecc1c66829d291b2f2fb1a27329d152f212e6 # v0.1.3

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@7ec5c2b0c6cdda6e8bbb49444bc797dd33d74dd8 # v5.0.0
        with:
          install-only: true

      - name: Run goreleaser snapshot
        run: make snapshot

      - name: check binary
        run: ./dist/mdtoc-amd64-linux -version
